name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: |
        pip install pandas numpy scipy scikit-learn gymnasium transformers pytest datasets accelerate python-dotenv stable-baselines3
    - run: |
        export PYTHONPATH="${PYTHONPATH}:."
        pytest -v