name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Set up Miniconda and install mamba
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          python-version: 3.10
          use-mamba: true
          activate-environment: fr_sent_ml
          environment-file: environment.yml
          mamba-version: latest   # ensures compatibility with Python 3.10

      # 3. Optional: install pip-only packages
      - name: Install pip packages
        run: |
          pip install --upgrade pip
          pip install datasets accelerate

      # 4. Test environment with pytest
      - name: Run tests
        run: |
          pytest -v
