name: Run Conda Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: myenv
        environment-file: env.yml
        python-version: 3.10  # Optional, overrides env.yml if mismatch
        auto-activate-base: false

    - name: Verify environment
      run: conda info --envs

    - name: Install test dependencies
      shell: bash -l {0}
      run: |
        conda activate myenv
        pip install pytest

    - name: Run tests with pytest
      shell: bash -l {0}
      run: |
        conda activate myenv
        pytest tests/
