name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Miniconda with Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          mamba-version: 1.3.1
          python-version: 3.10
          environment-file: environment.yml
          activate-environment: fr_sent_ml
          use-mamba: true
          verbose: true

      - name: Install pip packages separately
        run: |
          pip install --upgrade pip
          pip install datasets accelerate

      - name: Test environment
        run: |
          pytest -v
